[project]
name = "frontend"
version = "0.1.0"
description = "Add a short description here"
authors = ["Yousifff <yousifsayer@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
main = "pixi run streamlit run app.py"


[dependencies]
streamlit = ">=1.33.0,<1.34"

[pypi-dependencies]
st-pages = "*"
