[project]
name = "backend"
version = "0.1.0"
description = "Add a short description here"
authors = ["yousif <yousifsayer@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
api = "uvicorn main:app --reload"

[dependencies]
fastapi = ">=0.110.1,<0.111"
sqlmodel = ">=0.0.14,<0.1"
uvicorn = ">=0.29.0,<0.30"
